---
title: "Example"
output:
  html_document: default
  pdf_document: default
  word_document: default
date: "2024-02-18"
---





```{r, echo=FALSE}
library(knitr)
library(devtools)
devtools::install_github("bitarellolab/balselr")
library(balselr)
hook_output <- knit_hooks$get("output")
knit_hooks$set(output = function(x, options) {
  lines <- options$output.lines
  if (is.null(lines)) {
    return(hook_output(x, options))  # pass to default hook
  }
  x <- unlist(strsplit(x, "\n"))
  more <- "..."
  if (length(lines)==1) {        # first n lines
    if (length(x) > lines) {
      # truncate the output, but add ....
      x <- c(head(x, lines), more)
    }
  } else {
    x <- c(more, x[lines], more)
  }
  # paste these lines together
  x <- paste(c(x, ""), collapse = "\n")
  hook_output(x, options)
})
``` 

### Install `balselr`

```{r, echo=TRUE, eval=F}
library(devtools)
devtools::install_github("bitarellolab/balselr")
library(balselr)
```




```{r, output.lines=10}
library(balselr)
#Read In the VCF File
read_vcf(x=system.file(package="balselr", "example.vcf"))
```

```{r, output.lines=10}

#Parse the VCF Files
ncd1_input <-parse_vcf(infile=system.file(package="balselr", "example.vcf"), n0=108, type="ncd1")
```


```{r, output.lines=10}

#Run ncd1 Test
ncd1(ncd1_input)
```


