#' Parse VCF files generated by SLiM v3
#'
#' @param infile The path and name of a vcf file - single chromosome
#' @param n0 Number of individuals in pop0. Must be >=2 for both ncd1 and ncd2.
#' @param n1 Number of individuals in pop1. Must be >=1 for ncd2. Must be NULL for ncd1. NULL by default.
#' @param type Which input format will be generated. Options: ncd1, ncd2.
#' @return Returns a data table object with columns CHR   POS REF ALT tx_1 tn_1 (if type is ncd1) or  CHR   POS REF ALT tx_1 tn_1 tx_2 tn_2 (if type is ncd2)
#' @export
#' @examples parse_vcf(infile=system.file(package="balselr", "example.vcf"), n0=108, type="ncd1")
#' @examples parse_vcf(infile=system.file(package="balselr", "example.vcf"), n0=108, n1=1, type="ncd2")
#' @param verbose Logical. Printed updates. Default is T.

# to do: test that outputs of both commands in the examples have the same values for tx_1 and tn_1
parse_vcf <- function(infile = NULL,
                      n0 = NULL,
                      n1 = NULL,
                      type = NULL,
                      verbose=T) {

        assertthat::assert_that(file.exists(infile),
                                msg = glue::glue("VCF file {infile} does not exist.\n"))
        #to do: check that n0 and n1 meet requirements outlined above.
        #to do: check that vcf file has at least the number of individuals provided in n0+n1 (i.e., if users says n0=10, n1=1 but vcf only has 8 individuals, this should return an error as early as possible)
        type <- tolower(type)
        assertthat::assert_that(type %in% c("ncd1", "ncd2"), msg = "ncd_type must be either ncd1 or ncd2.\n")
        if (type == "ncd2") {
                assertthat::assert_that(is.null(n1) == FALSE, msg = "n1 cannot be 'NULL'. NCD2 requires an outgroup at least one individual as an outgroup.")
        }
        inp <- read_vcf(x = infile)
        nind<-c(n0,n1)
        index.col <- which(colnames(inp) == "FORMAT") + 1
        if (type == "ncd2") {
                res <-
                        .vcf_ncd2(
                                x = inp,
                                nind = nind,
                                index.col = index.col,
                                verbose = verbose
                        )
        } else if (type == "ncd1") {
                res <-
                        .vcf_ncd1(
                                x = inp,
                                nind = nind,
                                index.col = index.col,
                                verbose = verbose
                        )
        }
        return(res)
}
